In [1]:
import numpy as np
import pandas as pd

Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [4]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [6]:
numb = a.size
for i in range(numb - 1, 1, -1):
    if (numb % i == 0):
        print(i, end = " ")

6 4 3 2 

In [12]:
a1 = a.reshape(6, 2)
a2 = a.reshape(4, 3)
a3 = a.reshape(3, 4)
a4 = a.reshape(2, 6)
a5 = a.reshape(12, 1)

display(a1, a2, a3, a4, a5)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [13]:
a6 = a.reshape(-1, 2)
a7 = a.reshape(-1, 3)
a8 = a.reshape(3, -1)
a9 = a.reshape(2, -1)
a10 = a.reshape(12, -1)

display(a6, a7, a8, a9, a10)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

Q: Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным? 
A: Нет, a10.ndim = 2

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [16]:
in_arr = np.random.randn(3, 4)
out_arr = in_arr.flatten()

display(in_arr, in_arr.size, out_arr, out_arr.size)

array([[ 0.04857702, -0.2274434 , -0.402479  ,  0.41191888],
       [-0.96526051,  0.60980887, -1.68506727,  0.44680872],
       [ 0.37938582, -0.39906597, -1.42792639,  0.52255379]])

12

array([ 0.04857702, -0.2274434 , -0.402479  ,  0.41191888, -0.96526051,
        0.60980887, -1.68506727,  0.44680872,  0.37938582, -0.39906597,
       -1.42792639,  0.52255379])

12

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [22]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. 

Q: В чем разница между массивами a и b?
A: а - одномерный, b - двумерный

In [24]:
b = a.reshape(-1,1)
b

array([[20],
       [18],
       [16],
       [14],
       [12],
       [10],
       [ 8],
       [ 6],
       [ 4],
       [ 2]])

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [30]:
a = np.zeros((2, 2))
b = np.ones((3,2))
c = np.vstack((a,b))
#c = np.concatenate((a,b), axis = 0)
display(a,b,c)

array([[0., 0.],
       [0., 0.]])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. 

Q: Какой размер имеет матрица B? 
A: 16

Q: Получится ли вычислить обратную матрицу для матрицы B и почему?
A: Нет, т.к. B - квадратная матрица с определителем 0

In [36]:
a = np.arange(0, 12)
A = a.reshape(4,3)
At = A.transpose()
B = np.dot(A, At)
#B = A.dot(At)
display(a, A, At, B, B.size, np.linalg.det(B))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

16

0.0

Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [47]:
np.random.seed(42)
print(np.random.random())

0.3745401188473625


Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [51]:
c = np.random.randint(0, 16, 16)
c

array([ 7,  2,  5,  4,  1,  7, 11, 13,  5,  1, 15, 11,  4,  0, 11,  9])

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [67]:
C = c.reshape((int(np.sqrt(c.size))), -1)
#C * 10
D = B + (C * 10)
D_det = np.linalg.det(D)
D_inv = np.linalg.inv(D)

display(C, D, D_det, D_inv)

array([[ 7,  2,  5,  4],
       [ 1,  7, 11, 13],
       [ 5,  1, 15, 11],
       [ 4,  0, 11,  9]])

array([[ 75,  34,  73,  72],
       [ 24, 120, 196, 252],
       [ 73,  96, 299, 322],
       [ 72, 122, 322, 392]])

33790400.00000005

array([[ 0.01610043, -0.00531689, -0.00816208,  0.00716535],
       [ 0.00715114,  0.02249692,  0.00430063, -0.01930844],
       [-0.0055933 ,  0.00488364,  0.03278919, -0.02904612],
       [-0.00058833, -0.01003658, -0.02677328,  0.03110351]])

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [68]:
D_inv[D_inv > 0] = 1
D_inv[D_inv < 0] = 0
D_inv

array([[1., 0., 0., 1.],
       [1., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 1.]])

In [74]:
E = np.where(D_inv == 1, B, C)
E

array([[  5,   2,   5,  32],
       [ 14,  50,  86,  13],
       [  5,  86, 149,  11],
       [  4,   0,  11, 302]])